import Link from 'next/link';
import ProductCard from '@/components/ProductCard';
import {products,cases} from '@/lib/data';
export default function Home(){const featured=products.slice(0,8);const visualCases=cases.filter(c=>c.status==='complete'&&c.hero).slice(0,4);return <>
<section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Architectural porcelain • Direct-import value</p><h1>Premium Porcelain Tile.<br/><span>$1.95 Per Sq. Ft.</span></h1><p className="hero-lead">Large-format porcelain for architects, builders, developers, contractors and residential projects—sourced globally and delivered nationwide.</p><div className="button-row"><Link className="button button-dark" href="/porcelain-tile/">Explore Porcelain</Link><Link className="button button-light" href="/request-quote/">Request Project Quote</Link></div><p className="microcopy">Free nationwide delivery on orders over 3,000 sq. ft.</p></div><div className="hero-media">{products[0].images[0]&&<img src={products[0].images[0]} alt="Calacatta Vena polished porcelain tile by Falcor Surfaces"/>}<div className="hero-price"><span>Current collection</span><strong>$1.95</strong><small>per sq. ft.</small></div></div></div></section>
<section className="value-strip"><div className="shell value-grid"><div><strong>$1.95</strong><span>Premium porcelain / sq. ft.</span></div><div><strong>Nationwide</strong><span>Commercial & residential delivery</span></div><div><strong>Over 3,000</strong><span>Sq. ft. qualifies for free delivery</span></div><div><strong>Florida</strong><span>Miami • Tampa • Orlando network</span></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Explore the collection</p><h2>Architectural porcelain without the architectural markup.</h2></div><Link className="text-link" href="/porcelain-tile/">View all porcelain →</Link></div><div className="product-grid">{featured.map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
<section className="section section-dark"><div className="shell two-col"><div><p className="eyebrow light">Why Falcor</p><h2>Global sourcing. Florida logistics. Project-scale value.</h2></div><div className="large-copy"><p>Falcor Surfaces sources porcelain through manufacturing relationships in Spain, Italy, Turkey and other international production markets. The result is a focused collection of premium-grade formats offered at a straightforward $1.95 per square foot.</p><p>We support real estate groups, architects, general contractors, builders, subcontractors, corporate buyers and local residential clients from our Boca Raton headquarters and Florida warehouse network.</p><Link className="button button-outline" href="/architects-builders/">Architects & Trade</Link></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Design applications</p><h2>See how the collection works in space.</h2></div><Link className="text-link" href="/case-studies/">View all studies →</Link></div><div className="case-grid">{visualCases.map(c=><Link key={c.slug} href={`/case-studies/${c.slug}/`} className="case-card"><img src={c.hero!} alt={`Design visualization featuring ${c.product} porcelain tile`}/><div><p className="eyebrow">{c.product}</p><h3>{c.title}</h3><span>View application →</span></div></Link>)}</div></div></section>
<section className="section stone"><div className="shell two-col"><div><p className="eyebrow">Commercial capability</p><h2>Made for specifications. Priced for square footage.</h2></div><div className="benefit-list"><div><strong>Technical clarity</strong><p>Size, finish, thickness, PEI, absorption, edge and shade information presented cleanly on every product page.</p></div><div><strong>Project logistics</strong><p>Nationwide delivery with free delivery over 3,000 square feet, supported by Florida warehouse operations.</p></div><div><strong>Residential welcome</strong><p>Commercial pricing is available to local homeowners and renovation projects as well.</p></div></div></div></section>
<section className="cta-band"><div className="shell cta-inner"><div><p className="eyebrow light">Planning a project?</p><h2>Get porcelain pricing, availability and delivery coordination.</h2></div><Link className="button button-white" href="/request-quote/">Request a Quote</Link></div></section>
</>}
